import { useEffect, useRef, useState } from 'react'
import { supabase, isSupabaseConfigured } from '../lib/supabase'

const PLACEHOLDER_DESC = 'Original link saved.'
const CONCURRENCY = 2
const RETRY_AFTER_MS = 30_000

function isAllDigits(s) {
  return /^\d{6,}$/.test(String(s || '').trim())
}

function isBareHandle(s) {
  return /^@[\w.]+$/.test(String(s || '').trim())
}

function isWeakDesc(desc) {
  const d = String(desc || '').trim()
  if (!d) return true
  if (d === PLACEHOLDER_DESC) return true
  if (d === 'Post on X') return true
  if (isBareHandle(d)) return true
  if (d.length < 8) return true
  // YouTube-specific placeholders generated by Gemini or similar
  if (d.includes('Shared video link without description')) return true
  if (d === 'Shared video link without description.') return true
  return false
}

function titleLooksRaw(title, href) {
  const t = String(title || '').trim()
  if (!t) return true
  if (isAllDigits(t)) return true
  if (t.includes('/')) return true
  
  // YouTube-specific weak titles
  if (t === '@watch' || t === '@shorts') return true
  // Video ID-looking handles (typically 11 chars for YouTube)
  if (/^@[A-Za-z0-9_-]{8,15}$/.test(t)) {
    // If it's a YouTube URL, this is likely a video ID handle, not a real title
    try {
      if (href) {
        const u = new URL(href)
        const host = u.hostname.replace(/^www\./, '').toLowerCase()
        if (host === 'youtube.com' || host === 'youtu.be' || host === 'm.youtube.com' || host === 'music.youtube.com') {
          return true
        }
      }
    } catch {
      /* ignore */
    }
  }
  
  try {
    if (href) {
      const u = new URL(href)
      const hostPath = u.hostname.replace(/^www\./, '') + u.pathname
      if (t === hostPath || t === u.hostname + u.pathname) return true
    }
  } catch {
    /* ignore */
  }
  return false
}

/**
 * Whether a link share still needs /api/unfurl backfill.
 * Bare @handle title always needs enrich even if description looks nonempty
 * but is also weak/handle-like.
 */
export function needsEnrich(share) {
  if (!share) return false
  if (share.kind && share.kind !== 'link') return false
  const href = share.href || share.url
  if (!href) return false
  if (!share.id) return false

  const title = (share.title || '').trim()
  const desc = (share.description || '').trim()

  if (isWeakDesc(desc)) return true
  if (titleLooksRaw(title, href)) return true
  // Bare @handle title always needs enrich
  if (isBareHandle(title)) return true
  return false
}

/**
 * After messages load, unfurl weak link shares (concurrency 2),
 * patch local state + original_shares so content sticks.
 * Only marks attempted on success; failures go to a failed set and retry once after 30s.
 */
export function useEnrichShares(messages, setMessages) {
  const attemptedRef = useRef(new Set())
  /** @type {React.MutableRefObject<Map<string, { at: number, retries: number }>>} */
  const failedRef = useRef(new Map())
  const runningRef = useRef(false)
  const [retryTick, setRetryTick] = useState(0)

  useEffect(() => {
    if (!isSupabaseConfigured || !supabase || !setMessages) return undefined
    if (!Array.isArray(messages) || !messages.length) return undefined

    const now = Date.now()
    const weak = []
    let soonestRetry = null

    for (const m of messages) {
      const share = m.share
      if (!share?.id) continue
      if (attemptedRef.current.has(share.id)) continue
      if (!needsEnrich(share)) continue

      const fail = failedRef.current.get(share.id)
      if (fail) {
        if (fail.retries >= 1) {
          // Already retried once — wait for a later messages change / manual refresh
          continue
        }
        const readyAt = fail.at + RETRY_AFTER_MS
        if (now < readyAt) {
          const wait = readyAt - now
          if (soonestRetry == null || wait < soonestRetry) soonestRetry = wait
          continue
        }
      }
      weak.push({ share })
    }

    let retryTimer
    if (soonestRetry != null && !weak.length) {
      retryTimer = setTimeout(() => setRetryTick((t) => t + 1), soonestRetry + 20)
      return () => clearTimeout(retryTimer)
    }

    if (!weak.length) return undefined
    if (runningRef.current) return undefined

    let cancelled = false
    runningRef.current = true

    ;(async () => {
      let cursor = 0

      async function worker() {
        while (!cancelled) {
          const idx = cursor++
          if (idx >= weak.length) return
          const { share } = weak[idx]
          const href = share.href || share.url
          try {
            const { data: sessionData } = await supabase.auth.getSession()
            const token = sessionData?.session?.access_token
            if (!token) {
              const prev = failedRef.current.get(share.id)
              failedRef.current.set(share.id, {
                at: Date.now(),
                retries: prev ? prev.retries + 1 : 0,
              })
              continue
            }

            const resp = await fetch('/api/unfurl', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
                Authorization: `Bearer ${token}`,
              },
              body: JSON.stringify({ url: href }),
            })
            if (!resp.ok) {
              const prev = failedRef.current.get(share.id)
              failedRef.current.set(share.id, {
                at: Date.now(),
                retries: prev ? prev.retries + 1 : 0,
              })
              continue
            }
            const meta = await resp.json()
            if (!meta?.title && !meta?.description) {
              const prev = failedRef.current.get(share.id)
              failedRef.current.set(share.id, {
                at: Date.now(),
                retries: prev ? prev.retries + 1 : 0,
              })
              continue
            }

            const title = meta.title
              ? String(meta.title).slice(0, 120)
              : share.title
            const description =
              meta.description != null && meta.description !== ''
                ? String(meta.description).slice(0, 240)
                : share.description
            const platform = meta.platform || share.platform
            const byline = meta.byline || share.byline || share.metadata?.byline

            // Still bare-handle with no real text — treat as failure (allow retry)
            if (isBareHandle(title) && isWeakDesc(description)) {
              const prev = failedRef.current.get(share.id)
              failedRef.current.set(share.id, {
                at: Date.now(),
                retries: prev ? prev.retries + 1 : 0,
              })
              continue
            }

            if (cancelled) return

            // Mark attempted ONLY after successful meta applied
            attemptedRef.current.add(share.id)
            failedRef.current.delete(share.id)

            setMessages((prev) =>
              prev.map((m) => {
                if (m.share?.id !== share.id) return m
                return {
                  ...m,
                  share: {
                    ...m.share,
                    title,
                    description,
                    platform,
                    byline,
                    metadata: {
                      ...(m.share.metadata || {}),
                      ...(byline ? { byline } : {}),
                    },
                  },
                }
              })
            )

            const patch = {
              title,
              description,
              ...(byline
                ? {
                    metadata: {
                      ...(share.metadata || {}),
                      byline,
                    },
                  }
                : {}),
            }
            const { error } = await supabase
              .from('original_shares')
              .update(patch)
              .eq('id', share.id)
            if (error) {
              console.warn(
                'enrich share DB update failed (check RLS / migration 006)',
                share.id,
                error
              )
            }
          } catch (e) {
            console.warn('enrich share failed', share.id, e)
            const prev = failedRef.current.get(share.id)
            failedRef.current.set(share.id, {
              at: Date.now(),
              retries: prev ? prev.retries + 1 : 0,
            })
          }
        }
      }

      const n = Math.min(CONCURRENCY, weak.length)
      await Promise.all(Array.from({ length: n }, () => worker()))
      runningRef.current = false

      // If anything is waiting for a retry, schedule tick
      let nextWait = null
      const t = Date.now()
      for (const [, fail] of failedRef.current) {
        if (fail.retries >= 1) continue
        const wait = fail.at + RETRY_AFTER_MS - t
        if (wait > 0 && (nextWait == null || wait < nextWait)) nextWait = wait
        else if (wait <= 0) nextWait = 0
      }
      if (nextWait != null && !cancelled) {
        setTimeout(() => setRetryTick((x) => x + 1), Math.max(20, nextWait))
      }
    })()

    return () => {
      cancelled = true
      runningRef.current = false
      if (retryTimer) clearTimeout(retryTimer)
    }
  }, [messages, setMessages, retryTick])
}
